-- FACULTY
CREATE TABLE FACULTY (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL
);

-- Department
CREATE TABLE DEPARTMENT (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR (20) NOT NULL,
  FACULTY_ID INTEGER REFERENCES FACULTY(ID)
);

--LECTURE HALL
CREATE TABLE LECTURE_HALL (
  ID SERIAL PRIMARY KEY,
  NUMBER_HALL VARCHAR(20) NOT NULL
);

-- GROUP
CREATE TABLE GROUPS(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  COURSE INTEGER,
  DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT(ID)
);

-- STUDENT
CREATE TABLE STUDENT (
  ID SERIAL PRIMARY KEY,
  CARD_NUMBER VARCHAR(20) NOT NULL ,
  NAME VARCHAR(20) NOT NULL,
  SURNAME VARCHAR(20) NOT NULL,
  ADDRESS VARCHAR(30) NOT NULL,
  GROUPS_ID INTEGER REFERENCES GROUPS(ID)
);

-- SUBJECT
CREATE TABLE SUBJECT (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT(ID)
);

-- TEACHER
CREATE TABLE TEACHER (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  SURNAME VARCHAR(20) NOT NULL,
  ADDRESS VARCHAR(30) NOT NULL,
  POSITION VARCHAR (20) NOT NULL,
  DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT(ID)
);

-- Schedule
CREATE TABLE SCHEDULE (
  ID SERIAL PRIMARY KEY,
  LOCATION INTEGER REFERENCES LECTURE_HALL(ID),
  SUBJECT_ID INTEGER REFERENCES SUBJECT(ID),
  TEACHER_ID INTEGER REFERENCES TEACHER(ID),
  GROUP_ID INTEGER REFERENCES GROUPS(ID),
  DATE DATE
);

CREATE TABLE TEACHER_SUBJECT (
  ID SERIAL PRIMARY KEY,
  TEACHER_ID INTEGER REFERENCES TEACHER(ID),
  SUBJECT_ID INTEGER REFERENCES SUBJECT(ID)
);
